--- #YAML:1.0
name:                Syntax-SourceHighlight
version:             1.1.1
abstract:            Perl Binding to GNU Source Highlight
license:             Public Domain
author:              Thomas Chust <chust@web.de>
distribution_type:   module
dynamic_config:      1
configure_requires:
    File::Spec: 0
    File::Copy: 0
    Archive::Tar: 0
    ExtUtils::PkgConfig: 1.12
build_requires:
    Test::Simple: 0
requires:
    File::Spec: 0
provides:
    Syntax::SourceHighlight: 1.1.1
resources:
    repository: https://code.launchpad.net/~chust/+junk/SourceHighlight
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
