--- #YAML:1.0
name:                Syntax-SourceHighlight
version:             1.0.2
abstract:            Perl Binding to GNU Source Highlight
license:             Public Domain
author:              Thomas Chust <chust@web.de>
distribution_type:   module
dynamic_config:      1
configure_requires:
    ExtUtils::PkgConfig: 1.12
build_requires:
    Test::Simple: 0
requires:
provides:
    Syntax::SourceHighlight: 1.0.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
